import uuid
import logging
from typing import List, Optional, Any
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.repositories.base import BaseRepository
from app.models.evidence import Evidence
from app.repositories.investigation_repository import RepositoryException

logger = logging.getLogger("app.repositories.EvidenceRepository")

class EvidenceRepository(BaseRepository[Evidence]):
    """Repository handling database operations for the Evidence entity."""

    def __init__(self, db_session: AsyncSession):
        super().__init__(Evidence, db_session)

    async def create(self, obj_in: Any) -> Evidence:
        """Creates a new Evidence record."""
        try:
            logger.info("Creating new evidence record.")
            if isinstance(obj_in, Evidence):
                self.db.add(obj_in)
                await self.db.commit()
                await self.db.refresh(obj_in)
                return obj_in
            return await super().create(obj_in=obj_in)
        except Exception as e:
            logger.error("Error creating evidence: %s", str(e))
            await self.db.rollback()
            raise RepositoryException(f"Failed to create evidence: {str(e)}")

    async def list_by_investigation(self, investigation_id: uuid.UUID) -> List[Evidence]:
        """Fetch all evidence items associated with a specific investigation."""
        try:
            logger.info("Listing evidence for investigation ID: %s", investigation_id)
            result = await self.db.execute(
                select(Evidence)
                .filter(Evidence.investigation_id == investigation_id)
                .order_by(Evidence.created_at.asc())
            )
            return list(result.scalars().all())
        except Exception as e:
            logger.error("Error listing evidence for investigation ID %s: %s", investigation_id, str(e))
            raise RepositoryException(f"Failed to list evidence: {str(e)}")

    async def list_by_agent(self, agent_result_id: uuid.UUID) -> List[Evidence]:
        """Fetch all evidence items generated by a specific agent execution result."""
        try:
            logger.info("Listing evidence for agent result ID: %s", agent_result_id)
            result = await self.db.execute(
                select(Evidence)
                .filter(Evidence.agent_result_id == agent_result_id)
                .order_by(Evidence.created_at.asc())
            )
            return list(result.scalars().all())
        except Exception as e:
            logger.error("Error listing evidence for agent result ID %s: %s", agent_result_id, str(e))
            raise RepositoryException(f"Failed to list evidence by agent: {str(e)}")

    async def list_by_severity(self, severity: str) -> List[Evidence]:
        """Fetch all evidence items filtered by severity level (e.g. HIGH, MEDIUM)."""
        try:
            logger.info("Listing evidence by severity: %s", severity)
            result = await self.db.execute(
                select(Evidence)
                .filter(Evidence.severity == severity)
                .order_by(Evidence.created_at.desc())
            )
            return list(result.scalars().all())
        except Exception as e:
            logger.error("Error listing evidence by severity %s: %s", severity, str(e))
            raise RepositoryException(f"Failed to list evidence by severity: {str(e)}")
